CXX=g++

DEPEND=stack.o Worker.cpp TaskScheduler.cpp Accirr.cpp

ACCIRR_HOME := /path/to/accirr

vpath %.cpp $(ACCIRR_HOME)/system
vpath %.o $(ACCIRR_HOME)/system

CXXFLAGS+= -O2 -I$(ACCIRR_HOME)/system 

all:$(TARGET)

$(TARGET):$(DEPEND)

.PHONY:clean
clean:
	rm -f $(TARGET)



