CXX=g++

DEPEND += stack.o Worker.cpp TaskScheduler.cpp Accirr.cpp -lsqlite3

ACCIRR_HOME := /path/to/accirr

vpath %.cpp $(ACCIRR_HOME)/system
vpath %.cpp $(ACCIRR_HOME)/third_party/intelpcm
vpath %.o $(ACCIRR_HOME)/system

CXXFLAGS += -O2 -I$(ACCIRR_HOME)/system -I$(ACCIRR_HOME)/third_party/intelpcm

all:$(TARGET)

$(TARGET):$(DEPEND)

.PHONY:clean
clean:
	rm -f $(TARGET)



