CXX=g++

DEPEND += stack.o Worker.cpp TaskScheduler.cpp Accirr.cpp 

LIB += -lsqlite3

ACCIRR_HOME := /path/to/accirr

PCM_DIR := $(ACCIRR_HOME)/third_party/intelpcm

vpath %.cpp $(ACCIRR_HOME)/system
vpath %.cpp $(ACCIRR_HOME)/third_party/intelpcm
vpath %.o $(ACCIRR_HOME)/system

CXXFLAGS += -O2 -I$(ACCIRR_HOME)/system -I$(PCM_DIR)



