PREFETCH := -DDATA_PREFETCH

MODE := -DPREFECH_MODE=1

LOCALICY := -DPREFETCH_LOCALITY=3

CXXFLAGS += $(PREFETCH) $(MODE) $(LOCALICY)
TARGET=pointer_tracing old_pointer_tracing pttest mppttest mtpttest
include ../Makefile

